### ISSUE TITLE
Visualization failure following the docs

### ISSUE THREAD

**Issue by amirstar** [hustvl/MapTR#102]
Hi team! Thanks for the nice work!
I followed the docs you provided and completed the data preparation via this cmd: 
`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0 --canbus ./data`
and downloaded the checkpoints. Then I tried to visualize the data with this cmd (it is in CPU) : 
`python tools/maptr/vis_pred.py projects/configs/maptr/maptr_nano_r18_110e.py ckpts/resnet18-f37072fd.pth`
But got this error: 
```
/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py:120: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
Traceback (most recent call last):
  File "tools/maptr/vis_pred.py", line 399, in <module>
    main()
  File "tools/maptr/vis_pred.py", line 242, in main
    result = model(return_loss=False, rescale=True, **data)
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 48, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/MapTR/projects/mmdet3d_plugin/maptr/detectors/maptr.py", line 164, in forward
    return self.forward_test(**kwargs)
  File "/home/user/MapTR/projects/mmdet3d_plugin/maptr/detectors/maptr.py", line 311, in forward_test
    new_prev_bev, bbox_results = self.simple_test(
  File "/home/user/MapTR/projects/mmdet3d_plugin/maptr/detectors/maptr.py", line 365, in simple_test
    img_feats = self.extract_feat(img=img, img_metas=img_metas)
  File "/home/aghaderi/anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/user/MapTR/projects/mmdet3d_plugin/maptr/detectors/maptr.py", line 113, in extract_feat
    img_feats = self.extract_img_feat(img, img_metas, len_queue=len_queue)
  File "/home/user/MapTR/projects/mmdet3d_plugin/maptr/detectors/maptr.py", line 92, in extract_img_feat
    img_feats = self.img_backbone(img)
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 635, in forward
    x = self.conv1(x)
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 6-dimensional input of size [1, 1, 6, 3, 192, 320] instead
```

It seems that data is not as expected. Thank you for the help!

**Comment by amirstar** [comment]
I used the checkpoint from installation page. When I used the checkpoint from the Readme page with this command 
`python tools/maptr/vis_pred.py projects/configs/maptr/maptr_nano_r18_110e.py ckpts/maptr_nano_r18_110e.pth`
I got the same error and also this msg 
```
load checkpoint from local path: ckpts/maptr_nano_r18_110e.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: pts_bbox_head.transformer.encoder.layers.0.attentions.1.attention.grid_offsets

```
