### ISSUE TITLE
run vis_pred.py to show maptrv2 nuscenes with centerline  error

### ISSUE THREAD

**Issue by linClubs** [hustvl/MapTR#104]
Hi team! Thanks for the nice work!
I run `python tools/maptr/vis_pred.py projects/configs/maptrv2/maptrv2_nusc_r50_24ep.py ckpts/maptrv2_nusc_r50_24e.pth` was successful, but run
`python tools/maptr/vis_pred.py projects/configs/maptrv2/maptrv2_nusc_r50_24ep_w_centerline.py ckpts/maptrv2_nusc_r50_24ep_w_centerline.pth`

the terminal  showed as follow：
~~~
2023-09-13 16:14:49,847 - mmdet3d - INFO - BEGIN vis test dataset samples gt label & pred
[                                                  ] 0/162, elapsed: 0s, ETA:/home/lin/code/maptr2/MapTR/projects/mmdet3d_plugin/core/bbox/coders/nms_free_coder.py:242: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  bbox_index = indexs // self.num_classes
Traceback (most recent call last):
  File "tools/maptr/vis_pred.py", line 393, in <module>
    main()
  File "tools/maptr/vis_pred.py", line 307, in main
    plt.plot(x, y, color=colors_plt[gt_label_3d],linewidth=1,alpha=0.8,zorder=-1)
IndexError: list index out of range
~~~

How do i fix it? thanks

**Comment by LegendBC** [comment]
You should add extra color for the centerline semantic. We will update the visualization code and document in recent days.
