### ISSUE TITLE
ImportError with mmdet3d

### ISSUE THREAD

**Issue by Jiayiiiiiii502** [hustvl/MapTR#117]
When I generate dataset, there is an importerror though i have installed the essential package . Can anyone help please?

pip list | grep mm
comm                      0.1.4
mmcv-full                 1.4.0
mmdet                     2.14.0
mmdet3d                   0.17.2
mmsegmentation            0.14.1
timm                      0.9.5

pip list | grep torch
torch                     1.10.0+cu113
torchaudio                0.10.0+rocm4.1
torchvision               0.11.0+cu113

Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/root/autodl-tmp/MapTR/tools/data_converter/create_gt_database.py", line 11, in <module>
    from mmdet3d.core.bbox import box_np_ops as box_np_ops
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/core/bbox/__init__.py", line 5, in <module>
    from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/core/bbox/iou_calculators/__init__.py", line 2, in <module>
    from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 6, in <module>
    from ..structures import get_box_type
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/core/bbox/structures/__init__.py", line 2, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/core/bbox/structures/base_box3d.py", line 6, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/ops/__init__.py", line 11, in <module>
    from .ball_query import ball_query
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/ops/ball_query/__init__.py", line 1, in <module>
    from .ball_query import ball_query
  File "/root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: /root/miniconda3/envs/maptr/lib/python3.8/site-packages/mmdet3d/ops/ball_query/ball_query_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

**Comment by sobremesalin** [comment]
I met the same problem, did you solve this problem? Looking forward to your reply~
