### ISSUE TITLE
Can not find 

### ISSUE THREAD

**Issue by spcrobocar** [hustvl/MapTR#16]
When I prepared the data, I got the following error. How can I fix it? 

python tools/create_data.py nuscenes --root-path ./data --out-dir ./data --extra-tag nuscenes --version v1.0 --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/.../apps/MapTR/tools/data_converter/create_gt_database.py", line 6, in <module>
    from mmcv.ops import roi_align
  File ".../anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File ".../anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File ".../anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File ".../anaconda3/envs/maptr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by LegendBC** [comment]
Sorry for the late reply. You can refer to https://github.com/open-mmlab/mmdetection/issues/3271, it seems like that you did not install mmcv with correct version.
