### ISSUE TITLE
nuScenes dataset for MapTRv2 evatuation

### ISSUE THREAD

**Issue by otets-u** [hustvl/MapTR#161]
Thank you for great work.

Could you tell me which dataset I should prepare when I use nuScenes dataset??

Now, I'd like to try to run the evaluation script with nuScenes dataset.
I followed the below steps and downloaded the listed dataset from nuScenes.

[Train and Eval](https://github.com/hustvl/MapTR/blob/maptrv2/docs/train_eval.md)

Prepared Dataset

- can_bus.zip
- v1.0-test_meta.tgz
- v1.0-test_blobs.tgz
- v1.0-mini.tgz

And then, I encoutered the below error about dataset.
So, I'm trying to solve the error now.

```bash
$ ./tools/dist_test_map.sh ./projects/configs/maptrv2/maptrv2_nusc_r50_24ep_w_centerline.py ./ckpts/resnet50-19c8e357.pth 2

...

 img_neck.lateral_convs.0.conv.bias, img_neck.fpn_convs.0.conv.weight, img_neck.fpn_convs.0.conv.bias

[                                                  ] 0/6019, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/test.py", line 262, in <module>
    main()
  File "./tools/test.py", line 233, in main
    outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
  File "/opt/MapTR/projects/mmdet3d_plugin/bevformer/apis/test.py", line 70, in custom_multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/MapTR/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1393, in __getitem__
    return self.prepare_test_data(idx)
  File "/opt/MapTR/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1382, in prepare_test_data
    example = self.pipeline(input_dict)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/opt/MapTR/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 48, in __call__
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/opt/MapTR/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 48, in <listcomp>
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/mmcv/image/io.py", line 176, in imread
    check_file_exist(img_or_path,
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: ./data/nuscenes/samples/CAM_FRONT/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281439762460.jpg

Traceback (most recent call last):
  File "./tools/test.py", line 262, in <module>
    main()
  File "./tools/test.py", line 233, in main
    outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
  File "/opt/MapTR/projects/mmdet3d_plugin/bevformer/apis/test.py", line 70, in custom_multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/MapTR/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1393, in __getitem__
    return self.prepare_test_data(idx)
  File "/opt/MapTR/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1382, in prepare_test_data
    example = self.pipeline(input_dict)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/opt/MapTR/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 48, in __call__
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/opt/MapTR/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 48, in <listcomp>
    [mmcv.imread(name, self.color_type) for name in filename], axis=-1)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/mmcv/image/io.py", line 176, in imread
    check_file_exist(img_or_path,
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: ./data/nuscenes/samples/CAM_FRONT/n008-2018-08-31-11-37-23-0400__CAM_FRONT__1535730467862404.jpg

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 356) of binary: /opt/miniconda3/envs/maptr-v2/bin/python3
Traceback (most recent call last):
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/miniconda3/envs/maptr-v2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         ./tools/test.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2024-03-12_08:24:30
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 356)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2024-03-12_08:24:30
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 357)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************
```

**Comment by TetsuhiroUchidaSHM** [comment]
Hello.
Unfortunately, I've not solved it.

**Comment by otets-u** [comment]
Hello.
Unfortunately, I've not solved it.

**Comment by liaoqingPKU** [comment]
you generate nusences data with wrong data dir. You should use your data dir not just ./data/nuscenes
![image](https://github.com/hustvl/MapTR/assets/16679259/e0a1f702-40f1-4c3d-8fb9-15ca92a8042c)

**Comment by davidpengiupui** [comment]
Same problem
