### ISSUE TITLE
question about eval

### ISSUE THREAD

**Issue by cyn-liu** [hustvl/MapTR#18]
I run the command of `./tools/dist_test_map.sh  ./projects/configs/maptr/maptr_nano_r18_110e.py ./ckpts/maptr_nano_r18_110e.pth 1`
and meet the following problem:
```console
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/workspace/MapTR/projects/mmdet3d_plugin/datasets/map_utils/tpfp.py", line 57, in custom_tpfp_gen
    matrix = custom_polyline_score(
  File "/workspace/MapTR/projects/mmdet3d_plugin/datasets/map_utils/tpfp_chamfer.py", line 52, in custom_polyline_score
    if o.intersects(pline):
AttributeError: 'numpy.int64' object has no attribute 'intersects'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tools/test.py", line 262, in <module>
    main()
  File "./tools/test.py", line 258, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/workspace/MapTR/projects/mmdet3d_plugin/datasets/nuscenes_map_dataset.py", line 1482, in evaluate
    ret_dict = self._evaluate_single(result_files[name], metric=metric)
  File "/workspace/MapTR/projects/mmdet3d_plugin/datasets/nuscenes_map_dataset.py", line 1416, in _evaluate_single
    mAP, cls_ap = eval_map(
  File "/workspace/MapTR/projects/mmdet3d_plugin/datasets/map_utils/mean_ap.py", line 256, in eval_map
    tpfp = pool.starmap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'numpy.int64' object has no attribute 'intersects'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1584) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         ./tools/test.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2022-12-15_10:15:34
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 1584)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

```

Does anyone know the reason and solutions?

**Comment by LegendBC** [comment]
Sorry for late reply. It seems like that you installed the wrong version of shapely. You may try install shapely==1.8.5.post1

**Comment by cyn-liu** [comment]
> Sorry for late reply. It seems like that you installed the wrong version of shapely. You may try install shapely==1.8.5.post1

thanks, it's very useful for me.

**Comment by colahe** [comment]
> > Sorry for late reply. It seems like that you installed the wrong version of shapely. You may try install shapely==1.8.5.post1
> 
> thanks, it's very useful for me.



Hi, Could you tell me what dataset you used for evaluation pls?

**Comment by cyn-liu** [comment]
> 

nuScenes dataset
