### ISSUE TITLE
多卡训练失败

### ISSUE THREAD

**Issue by youhha** [hustvl/MapTR#183]
我使用4卡4090上训练maptr，nuscense数据集，出现以下报错，请问是什么原因呀
Traceback (most recent call last):
  File "./tools/train.py", line 260, in <module>
    main()
  File "./tools/train.py", line 249, in main 
    custom_train_model(
  File "/workspace/code/projects/mmdet3d_plugin/bevformer/apis/train.py", line 27, in custom_train_model  
    custom_train_detector(
  File "/workspace/code/projects/mmdet3d_plugin/bevformer/apis/mmdet_train.py", line 75, in custom_train_detector
    model = MMDistributedDataParallel(
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 496, in __init__   
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: replicas[0][0] in this process with sizes [80, 128] appears not to match sizes of the same param in process 0.

**Comment by WxlSky** [comment]
Great work! Thank you for sharing. I'm encountering this issue during multi-GPU training. What could be causing this problem? There were no issues with single-GPU training.

`
File "./tools/train.py", line 261, in <module>
    main()
  File "./tools/train.py", line 250, in main
    custom_train_model(
  File "/home/wxl/code/MapTR-main/projects/mmdet3d_plugin/bevformer/apis/train.py", line 27, in custom_train_model
    custom_train_detector(
  File "/home/wxl/code/MapTR-main/projects/mmdet3d_plugin/bevformer/apis/mmdet_train.py", line 199, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/wxl/.conda/envs/maptr/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'dict_keys' object`

**Comment by Astronirav** [comment]
@WxlSky I'm having the same problem. Were you able to find a solution?

**Comment by Geyi-FAN** [comment]
> [@WxlSky](https://github.com/WxlSky) I'm having the same problem. Were you able to find a solution?

I also met the same problem,Were you able to find a solution?🥺

**Comment by zhaoTimer** [comment]
@GeyiFan-better https://github.com/open-mmlab/mmdetection3d/issues/1364
