### ISSUE TITLE
problem of training

### ISSUE THREAD

**Issue by ygjwd12345** [hustvl/MapTR#19]
When I run the code with one gpu, I faced problem:
Traceback (most recent call last):
  File "tools/train.py", line 259, in <module>
    main()
  File "tools/train.py", line 215, in main
    model = build_model(
  File "/home/xx/data/MapTR/mmdetection3d/mmdet3d/models/builder.py", line 84, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xx/data/MapTR/mmdetection3d/mmdet3d/models/builder.py", line 57, in build_detector
    return DETECTORS.build(
  File "/home/xx/anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xx/anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xx/anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'MapTR is not in the models registry'
Could you help me fix this issue?

**Comment by ygjwd12345** [comment]
I use docker to solve this issue. But I found av2 looks useless and harmful.

**Comment by wbjsamuel** [comment]
I settle this problem by manually modifying the `~/anaconda3/envs/maptr/lib/python3.8/site-packages/mmcv.utils/registry.py` with
```def _register(module):
              self._register_module(module=module, module_name=name, force = True)
              return module
```
Hopefully, this will help those who meet the same problem and don't want to use docker to solve this issue.


> I use docker to solve this issue. But I found av2 looks useless and harmful.

**Comment by chuanye-Wang** [comment]
Could you share the docker image? really need it, thanks
